### PR TITLE
Stdout flush

### PR DESCRIPTION
**Pull request by kayb94**
Hi again,

I had issues with redirecting the output of packETHcli to a file. Nothing was in there, after I quit packETHcli with Ctrl+C (SIGINT). It's enough, to add some flushes.
I also unified the indentions to 4 spaces.

Regards

### CODE REVIEW

**Comment by jemcek** [comment]
Kay, there are some conflicts that must be resolved, could you check please?

**Comment by jemcek** [comment]
Closed and commited again.

**Comment by kayb94** [comment]
Thank you and sorry for reacting too slow ;)

**Comment by jemcek** [comment]
Hi @kayb94, you gave me some motivation so I pretty much rewrote the whole cli code. There are many new options now available. If you find some time you are welcome to try it. 

Miha

**Comment by kayb94** [comment]
Hi @jemcek, nice to hear that! To be honest I had some difficulties to see, what you actually did, because you made so many small commits recently. ;) You might be interested in this:

https://bugs.archlinux.org/task/60460?project=5&string=packeth

Someone has already been assigned. Since the everyone at Arch Linux is volunteering, it will probably take a while, if it is every incorporated.

Regards

**Pull request closed without merging**
