### PR TITLE
Prepare to migrate to GTK3

### PR DESCRIPTION
**Pull request by qarkai**
Related to #31 
- Convert Glade to GtkBuilder UI
- Split `packet_gen.ui` to separate files by widgets
- Remove unused files
- Use `GtkComboBoxText` instead of `GtkOptionMenu`
- Use theme icons until load from resource is supported
- Connect `on_optionmenu7_clicked` handler to `changed` signal
- Use `GtkTreeView` instead of `GtkCList`
- Use `GtkComboBoxText` instead of `GtkCombo`
- Remove unused `on_optionmenu23_clicked` handler
- Replace `gtk_notebook_set_page` with `gtk_notebook_set_current_page`
- Use `gtk_toggle_button_get_active`
- Use `gtk_widget_get_window`
- Remove unused support functions
- Remove outdated comments about generated Glade files

### CODE REVIEW

**Comment by qarkai** [comment]
I temporarily replaced pixmaps with themed icons. This is how application looks with my icon theme
image
@jemcek Probably you'd like to replace some pixmaps permanently.

**Comment by jemcek** [comment]
Hi, 

I can see you already did some work. I took a look into diffs, if I understand correctly, this is still code for gtk2, just we some changes that migration to gtk3 will be easier?

I'm not up to date with gtk3 requirements, so I need a little bit of intro to get a bigger picture?

Thanks for all the work and support.

**Comment by qarkai** [comment]
> Hi,
> 
> I can see you already did some work. I took a look into diffs, if I understand correctly, this is still code for gtk2, just we some changes that migration to gtk3 will be easier?

Yes, as described in https://docs.gtk.org/gtk3/migrating-2to3.html#preparations-in-gtk-2x

> I'm not up to date with gtk3 requirements, so I need a little bit of intro to get a bigger picture?

Well, nothing groundbreaking. Some widgets added, some removed and a bunch of API changes.

> Thanks for all the work and support.

**Comment by qarkai** [comment]
A polite ping. @jemcek is there anything you wait from me here?

**Comment by jemcek** [comment]
No, no, I'm just waiting for myself to find some time to proceed with this. 

I could compile and run it, the only thing a noticed is that some buttons have missing the pixmaps icon?
Screenshot 2023-10-01 at 20 50 38

Do you have any idea why, since I don't get any warning while running the app?

**Comment by qarkai** [comment]
Apparently your icon theme don't have "preferences-system" and "document-revert" icons although they listed in https://specifications.freedesktop.org/icon-naming-spec/latest/ar01s04.html.
Don't worry, icons from pixmap files could be restored after switching to GTK3.

**Comment by jemcek** [comment]
what are the final steps needed to switch the code to GTK3 at the end? 
All I could read is, that once the code is ready for gtk 2.24 there are only minor changes required but I could not find what exactly needs to be done?

**Comment by qarkai** [comment]
Change version in automake files (configure.ac), fix build errors (I'd fix warnings too), fix runtime errors/warnings in ui files. That's basically all.

**Comment by jemcek** [comment]
ok, thanks, it seems not a big deal. 

However I have some general questions:
1)  when I merge this Pull request, this won't break anything for current users I hope (besides the pixmaps maybe), so everyone running older distros would still be able to normally run and use packETH with their GTK2 installation? I could only test on Centos and Ubuntu and it seems ok
2) I have little experience with GTK3, but when we switch to GTK3, what does that mean for older distros, do they need to install gtk3 libraries and that's it? Should there be a seperate gtk2 and gtk3 version or is gtk3 so common that this should be the only version?

I'll try to do my best, and hopefully be able to push this forward soon. However I have some other issues I need to resolve, but they are waiting for the winter time :)

Besides this, are you satisfied with the program, are you missing something in particular? I didn't put much work into development lately, but honestly I don't have many good ideas either. It seems you are using the app, so I would appreciate any suggestion. 

Regards, Miha

**Comment by qarkai** [comment]
> ok, thanks, it seems not a big deal.
> 
> However I have some general questions:
> 
> 1. when I merge this Pull request, this won't break anything for current users I hope (besides the pixmaps maybe), so everyone running older distros would still be able to normally run and use packETH with their GTK2 installation? I could only test on Centos and Ubuntu and it seems ok

Not sure what you mean by 'run and use packETH'. If it's 'get sources, compile and run' then nothing should be changed.

> 2. I have little experience with GTK3, but when we switch to GTK3, what does that mean for older distros, do they need to install gtk3 libraries and that's it?

Sure it's the same as for GTK2.

> Should there be a seperate gtk2 and gtk3 version or is gtk3 so common that this should be the only version?

It's up to you and depends on how old distros are you going to support. Some *really* old distros like CentOS 6 even don't have GTK3 in repos, see https://repology.org/project/gtk/versions. On the other hand popular distros (CentOS, Debian, Fedora, Ubuntu) have decent GTK3 versions even in old releases, e.g. GTK3 3.18 in Ubuntu 16.04.
I would leave gtk3 version only.

> I'll try to do my best, and hopefully be able to push this forward soon. However I have some other issues I need to resolve, but they are waiting for the winter time :)
> 
> Besides this, are you satisfied with the program, are you missing something in particular? I didn't put much work into development lately, but honestly I don't have many good ideas either. It seems you are using the app, so I would appreciate any suggestion.

Sorry but no, I don't use application at all. I noticed it in https://archlinux.org/todo/gtk-2-eol/ and decided to help porting. Otherwise package could be removed from repos or have only cli part at best.

> Regards, Miha

**Review by jemcek — APPROVED** [review]

**Review by jemcek — APPROVED** [review]

**Pull request merged**
