### PR TITLE
Switch to GTK 3.16

### LINKED ISSUE #31: Port GUI to GTK3
Are there any plans since GTK2 is EOL?

### PR DESCRIPTION
**Pull request by qarkai**
* Replace/remove deprecated widgets and properties
* Remove activate_first_combo_box_item helper
* Remove deprecated GtkUIManager, GtkActionGroup, GtkAction for menu
* Remove deprecated gdk threads
* Load pixmaps and ui from resources
* Fix empty page in notebook4
* Fix GtkSeparator alignment
* Fix some warnings
* Remove duplicated pixmaps
* Remove obsolete patches
* Remove dev and unused pixmaps from dist
* Update README

Closes #31.

### CODE REVIEW

**Comment by jemcek** [comment]
Hi, thanks for the commits. 

I will review and test them, I hope to be able to do it in the following week.

**Comment by jemcek** [comment]
Hi, 

today I got a notification for a new commit (e63f087), is there a difference compared to one pushed a few days ago (64df866)?

**Comment by qarkai** [comment]
@jemcek Hi, just some code formatting. Diff: https://github.com/jemcek/packETH/compare/64df8668fc677222430effc59e7c551e8caa53fb..e63f0877c299a58fa84d4a066300ccfca454e215

**Comment by jemcek** [comment]
Hi, 

I'm testing the GTK3 version and what I found out is that all the entry fields are now much larger.
Before in most cases the entry boxes were adjusted to the max possible characters or digits that could be entered. Now the fields are much wider, it seems that after conversion this settings were lost. 

The look of the app window in GTK2 was so much nicer (easier to look at) than now at GTK3. 
I would like to correct this before publishing new release. It could take some time, because there are a lot of entries.

**Comment by qarkai** [comment]
It looks like GTK2's GtkEntry::max-length property changed its meaning in GTK3. See https://developer-old.gnome.org/gtk2/stable/GtkEntry.html#GtkEntry--max-length and https://docs.gtk.org/gtk3/property.Entry.max-length.html.
Now the same behavior could be achieved using https://docs.gtk.org/gtk3/property.Entry.width-chars.html.
I fixed that.

**Pull request merged**
